[package]
name = "bahlilui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
notify = "6.1"
futures-util = "0.3"
uuid = { version = "1.0", features = ["v4"] }
